// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Ns_FqR4llN0bcWRyKtQNvmRgo2r8ysY',
    appId: '1:364119674254:web:fb1619f6438c4da04e28df',
    messagingSenderId: '364119674254',
    projectId: 'interfaces-a8bf0',
    authDomain: 'interfaces-a8bf0.firebaseapp.com',
    storageBucket: 'interfaces-a8bf0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLo160r_wlBzibwrV9m2U8yd0Ux_6k5jE',
    appId: '1:364119674254:android:9c2c9f3273c926204e28df',
    messagingSenderId: '364119674254',
    projectId: 'interfaces-a8bf0',
    storageBucket: 'interfaces-a8bf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9znT9DnDux0W7SsZhPA-D63GpaIpa_W0',
    appId: '1:364119674254:ios:8a4d3481458d594d4e28df',
    messagingSenderId: '364119674254',
    projectId: 'interfaces-a8bf0',
    storageBucket: 'interfaces-a8bf0.firebasestorage.app',
    iosBundleId: 'com.example.interfaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9znT9DnDux0W7SsZhPA-D63GpaIpa_W0',
    appId: '1:364119674254:ios:8a4d3481458d594d4e28df',
    messagingSenderId: '364119674254',
    projectId: 'interfaces-a8bf0',
    storageBucket: 'interfaces-a8bf0.firebasestorage.app',
    iosBundleId: 'com.example.interfaces',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Ns_FqR4llN0bcWRyKtQNvmRgo2r8ysY',
    appId: '1:364119674254:web:0f088271ff62fdcc4e28df',
    messagingSenderId: '364119674254',
    projectId: 'interfaces-a8bf0',
    authDomain: 'interfaces-a8bf0.firebaseapp.com',
    storageBucket: 'interfaces-a8bf0.firebasestorage.app',
  );
}
